### ISSUE TITLE
Needs cursed annotations

### ISSUE THREAD

**Issue by valoeghese** [minecraft-cursed-legacy/cursed-fabric-loader#1]
`@Init`
`@PostInit`
`@Mod`
`@ClientInit`
`@ServerInit`

**Comment by coderbot16** [comment]
how too click clothes on someone else's issue

**Comment by valoeghese** [comment]
they're optional @coderbot16, so don't worry. They're planned to be converted by an annotation processor at compile time to non-cursed stuff.

**Comment by TwilightFlower** [comment]
that makes them honestly less cursed than the forge ones, i think they still runtime scan for those. also annotation processors generating anything but code in eclipse is HELL for some reason.

**Comment by ramidzkh** [comment]
OnlyIn and Dist instead of Environment and  EnvType

**Comment by valoeghese** [comment]
This will be moved to a separate project. Expect the unused annotations to be removed from cursed-fabric-loader in a future release

**Comment by valoeghese** [comment]
This issue has been closed as invalid

**Comment by ramidzkh** [comment]
pensieve
