### ISSUE TITLE
IllegalAccessException on launch

### ISSUE THREAD

**Issue by TwilightFlower** [minecraft-cursed-legacy/cursed-fabric-loader#4]
There are a few classes that are packaged. MinecraftServer is one of them. It happens to have a package-private or protected inner class. Something that gets repackaged by intermediary accesses this class.

`java.lang.IllegalAccessError: tried to access class net.minecraft.server.MinecraftServer$class_643 from class net.minecraft.class_139`

**Comment by Chocohead** [comment]
This was fixed in 8f014a3
